'use client';
import { useMemo, useState } from 'react';

function shape(x:number,a:number,b:number){return x<=0||x>=1?0:Math.pow(x,a-1)*Math.pow(1-x,b-1)}
function Curve({a,b,color}:{a:number;b:number;color:string}){const v=Array.from({length:81},(_,i)=>shape(i/80,a,b));const m=Math.max(...v,.0001);return <polyline points={v.map((n,i)=>`${i/80*100},${46-n/m*40}`).join(' ')} fill="none" stroke={color} strokeWidth="1.35" strokeLinejoin="round"/>}
function Title({n,title,text}:{n:string;title:string;text:string}){return <div className="section-title"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
function NumberField({label,value,set}:{label:string;value:number;set:(n:number)=>void}){return <label className="number-field"><span>{label}</span><input type="number" min="0" value={value} onChange={e=>set(Math.max(0,+e.target.value||0))}/><small>人</small></label>}
function Cell({count,rate,tone}:{count:number;rate:string;tone:string}){return <div className={`matrix-cell ${tone}`}><b>{rate}</b><span>{count} 人</span></div>}
type Round={doneBetter:number;doneSame:number;notDoneBetter:number;notDoneSame:number;doneBefore:number;notDoneBefore:number;doneN:number;notDoneN:number;doneSuccess:number;notDoneSuccess:number};
const series=[{key:'doneBefore',label:'完課組訓練前達標',color:'#d6a531'},{key:'doneBetter',label:'完課組訓練後進步',color:'#1f6fa8'},{key:'notDoneBetter',label:'未完課但反而進步',color:'#4d8cc4'},{key:'notDoneSame',label:'未完課且未進步',color:'#68758a'}] as const;
const completedTrend=[{key:'doneBefore',label:'完課組訓練前達標',color:'#d6a531'},{key:'doneBetter',label:'完課組訓練後進步',color:'#1f6fa8'}] as const;
const notCompletedTrend=[{key:'notDoneBefore',label:'未完課組訓練前達標',color:'#68758a'},{key:'notDoneBetter',label:'未完課組訓練後進步',color:'#4d8cc4'}] as const;
function PairChart({rounds,title,subtitle,keys}:{rounds:Round[];title:string;subtitle:string;keys:readonly [typeof series[number],typeof series[number]]}){const gap=18,w=Math.max(105,24+(rounds.length-1)*gap),x=(i:number)=>12+i*gap,points=(key:keyof Round)=>rounds.map((r,i)=>`${x(i)},${92-r[key]*.72}`).join(' '),chartKey=rounds.map(r=>`${r[keys[0].key]}-${r[keys[1].key]}`).join('|'),isNotCompleted=keys[0].key==='notDoneBetter';return <article className={`pair-chart${isNotCompleted?' not-completed-chart':''}`}><header><div><small>{subtitle}</small><h4>{title}</h4></div><div className="pair-legend">{keys.map((s,i)=><span key={s.key}><i style={{background:s.color}}/>{s.label}<b>{i===0?'訓練前基準':'訓練後結果'}</b></span>)}</div></header>{isNotCompleted?<div className="arrow-hint not-completed-rule"><span className="rise">▲ 綠色：未進步高出 ≥ 10 點</span><span className="neutral">◆ 灰色：差距 &lt; 10 點</span><span className="fall">▼ 紅色：反而進步高出 ≥ 10 點（需要檢查）</span></div>:<div className="arrow-hint"><span className="rise">▲ 綠色：訓練後上升</span><span className="fall">▼ 紅色：訓練後下降</span></div>}<div className="trend-scroll" key={chartKey}><svg viewBox={`0 0 ${w} 118`} style={{width:`${Math.max(620,rounds.length*70)}px`}} preserveAspectRatio="xMinYMin meet" role="img" aria-label={`${title}歷次機率折線圖`}>{[20,40,60,80,100].map(n=><g key={n}><line x1="10" y1={92-n*.72} x2={w-4} y2={92-n*.72} stroke="#d7dde8" strokeWidth=".28"/><text x="1" y={94-n*.72} fontSize="3" fill="#68758a">{n}%</text></g>)}{rounds.map((r,i)=>{const delta=isNotCompleted?r.notDoneSame-r.notDoneBetter:r[keys[1].key]-r[keys[0].key],state=isNotCompleted?(delta>=10?'up':delta<=-10?'down':'neutral'):(delta>=0?'up':'down'),color=state==='up'?'#1f6fa8':state==='down'?'#d6a531':'#68758a',xa=x(i),tip=state==='up'?`${xa-2},106 ${xa+2},106 ${xa},101`:state==='down'?`${xa-2},101 ${xa+2},101 ${xa},106`:`${xa},101 ${xa+2.2},103.5 ${xa},106 ${xa-2.2},103.5`;return <polygon key={`direction-${i}`} points={tip} fill={color}/>})}{keys.map((s,si)=><g key={s.key}><polyline points={points(s.key)} fill="none" stroke={s.color} strokeWidth="1.05" strokeLinejoin="round"/>{rounds.map((r,i)=><g key={i}><circle cx={x(i)} cy={92-r[s.key]*.72} r="1.35" fill="white" stroke={s.color} strokeWidth=".8"/><text x={x(i)} y={92-r[s.key]*.72+(si===0?-3.2:5.4)} textAnchor="middle" fontSize="2.8" fontWeight="700" fill={s.color}>{r[s.key].toFixed(1)}%</text></g>)}</g>)}{rounds.map((_,i)=><text key={i} x={x(i)} y="115" textAnchor="middle" fontSize="3.4" fill="#536176">第{i+1}次</text>)}</svg></div></article>}
function TrendChart({rounds}:{rounds:Round[]}){return <div className="split-trends"><PairChart rounds={rounds} title="完課組的訓練前後進步狀況" subtitle="COMPLETED GROUP · 前測 vs 後測" keys={[series[0],series[1]]}/><PairChart rounds={rounds} title="未完課組的結果分布" subtitle="NOT COMPLETED GROUP · 反而進步 vs 未進步" keys={[series[2],series[3]]}/></div>}
function GapChart({rounds}:{rounds:Round[]}){const latest=rounds[rounds.length-1].doneBetter-rounds[rounds.length-1].doneSame;return <div className="gap-panel"><div className="gap-copy"><span>FOCUS METRIC</span><h3>完課淨改善差距</h3><p>完課後進步率 − 完課後未進步率。<strong>高於 0 越多越好</strong>；低於 0 代表未進步者反而較多。</p><div className={latest>=0?'gap-score positive':'gap-score negative'}><small>最新差距</small><b>{latest>=0?'+':''}{latest.toFixed(1)}</b><em>百分點</em></div></div><div className="gap-chart-scroll"><div className="gap-chart" style={{width:`${Math.max(620,rounds.length*78)}px`}}>{rounds.map((r,i)=>{const g=r.doneBetter-r.doneSame;return <div className="gap-column" key={i}><div className="gap-track"><span>越高越好 ↑</span><i/><b className={g>=0?'positive':'negative'} style={g>=0?{height:`${g/2}%`,bottom:'50%'}:{height:`${Math.abs(g)/2}%`,top:'50%'}}/><em style={g>=0?{bottom:`calc(50% + ${g/2}% + 4px)`}:{top:`calc(50% + ${Math.abs(g)/2}% + 4px)`}}>{g>=0?'+':''}{g.toFixed(1)}</em></div><small>第 {i+1} 次</small></div>})}</div></div></div>}
function BaselineInputs({completedBefore,setCompletedBefore,notCompletedBefore,setNotCompletedBefore}:{completedBefore:number;setCompletedBefore:(n:number)=>void;notCompletedBefore:number;setNotCompletedBefore:(n:number)=>void}){return <section className="baseline-panel"><div><span>新增前測基準</span><h3>前後比較需要先知道訓練前表現</h3><p>請填入本批次在訓練前已達到目標表現的人數；確認輸入後會和訓練後進步率一起記錄。</p></div><div><NumberField label="完課組：訓練前達標人數" value={completedBefore} set={setCompletedBefore}/><NumberField label="未完課組：訓練前達標人數" value={notCompletedBefore} set={setNotCompletedBefore}/></div></section>}
function DemoButtons({generate}:{generate:(n:number)=>void}){return <section className="demo-panel"><div><span>持續觀測 · 範例模式</span><h3>不想逐筆輸入？直接載入範例</h3><p>選擇觀測次數後，系統會建立每班 20–30 人的示範資料，並同時生成訓練前基準與訓練後結果。</p></div><div className="demo-actions">{[5,10,15,20].map(n=><button key={n} onClick={()=>generate(n)} aria-label={`產生 ${n} 次持續觀測範例`}><b>{n}</b><span>次觀測範例</span><small>立即載入 ↗</small></button>)}</div></section>}
function erf(x:number){const s=x<0?-1:1,z=Math.abs(x),t=1/(1+.3275911*z),y=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-z*z);return s*y}
function normalCdf(x:number){return .5*(1+erf(x/Math.sqrt(2)))}

export default function Home(){
  const[prior,setPrior]=useState(50),[heads,setHeads]=useState(7);
  const[learners,setLearners]=useState(100),[completed,setCompleted]=useState(80),[completedBefore,setCompletedBefore]=useState(36),[completedImproved,setCompletedImproved]=useState(60),[notCompletedBefore,setNotCompletedBefore]=useState(2),[notCompletedImproved,setNotCompletedImproved]=useState(5),[rounds,setRounds]=useState<Round[]>([]),[priorMean,setPriorMean]=useState(50),[priorStrength,setPriorStrength]=useState(4),[threshold,setThreshold]=useState(5);
  const a=1+prior/100*8,b=1+(1-prior/100)*8,pa=a+heads,pb=b+10-heads;
  const posterior=useMemo(()=>Math.round(pa/(pa+pb)*100),[pa,pb]);
  const total=Math.max(1,learners),done=Math.min(total,completed),doneBetter=Math.min(done,completedImproved),notDone=total-done,doneSame=done-doneBetter,notDoneBetter=Math.min(notDone,notCompletedImproved),notDoneSame=notDone-notDoneBetter;
  const pct=(n:number,d:number)=>d?`${(n/d*100).toFixed(1)}%`:'—';
  const current:Round={doneBetter:done?doneBetter/done*100:0,doneSame:done?doneSame/done*100:0,notDoneBetter:notDone?notDoneBetter/notDone*100:0,notDoneSame:notDone?notDoneSame/notDone*100:0,doneBefore:done?Math.min(done,completedBefore)/done*100:0,notDoneBefore:notDone?Math.min(notDone,notCompletedBefore)/notDone*100:0,doneN:done,notDoneN:notDone,doneSuccess:doneBetter,notDoneSuccess:notDoneBetter};
  const confirmRound=()=>setRounds([...rounds,current]);
  const generateDemo=(count:number)=>{const random=(min:number,max:number)=>Math.floor(Math.random()*(max-min+1))+min,generated=Array.from({length:count},()=>{const t=random(20,30),d=random(Math.ceil(t*.65),Math.ceil(t*.95)),ds=random(Math.ceil(d*.55),Math.ceil(d*.9)),db=random(Math.ceil(d*.3),Math.ceil(d*.6)),nd=t-d,ns=nd?random(Math.floor(nd*.15),Math.ceil(nd*.55)):0,nb=nd?random(0,Math.ceil(nd*.4)):0;return{doneBetter:ds/d*100,doneSame:(d-ds)/d*100,notDoneBetter:nd?ns/nd*100:0,notDoneSame:nd?(nd-ns)/nd*100:0,doneBefore:db/d*100,notDoneBefore:nd?nb/nd*100:0,doneN:d,notDoneN:nd,doneSuccess:ds,notDoneSuccess:ns}});setRounds(generated);const last=generated[generated.length-1];setLearners(last.doneN+last.notDoneN);setCompleted(last.doneN);setCompletedBefore(Math.round(last.doneBefore/100*last.doneN));setCompletedImproved(last.doneSuccess);setNotCompletedBefore(Math.round(last.notDoneBefore/100*last.notDoneN));setNotCompletedImproved(last.notDoneSuccess)};
  const evidence=rounds.length?rounds:[current],sum=(k:keyof Round)=>evidence.reduce((n,r)=>n+r[k],0),dN=sum('doneN'),nN=sum('notDoneN'),dS=sum('doneSuccess'),nS=sum('notDoneSuccess'),priorA=priorMean/100*priorStrength,priorB=(1-priorMean/100)*priorStrength,dA=dS+priorA,dB=dN-dS+priorB,nA=nS+priorA,nB=nN-nS+priorB,dMean=dA/(dA+dB),nMean=nA/(nA+nB),dVar=dA*dB/((dA+dB)**2*(dA+dB+1)),nVar=nA*nB/((nA+nB)**2*(nA+nB+1)),diff=dMean-nMean,diffSd=Math.sqrt(dVar+nVar),probBetter=1-normalCdf((0-diff)/diffSd),probThreshold=1-normalCdf((threshold/100-diff)/diffSd),interval=(m:number,v:number)=>[Math.max(0,m-1.96*Math.sqrt(v))*100,Math.min(1,m+1.96*Math.sqrt(v))*100];
  return <main>
    <nav className="nav"><a className="brand" href="#top"><span>β</span> 貝氏直覺室</a><div><a href="#lab">互動實驗</a><a href="#training">訓練效益</a><a href="#compare">學派比較</a><a href="#case">生活案例</a></div></nav>
    <section className="hero" id="top"><div className="eyebrow">BAYESIAN STATISTICS · 從直覺開始</div><h1>新證據出現時，<br/><em>我們該如何改變想法？</em></h1><p>貝氏統計不是艱深的公式，而是一套更新信念的方法。先帶著原本的看法，再讓資料告訴我們應該移動多遠。</p><a className="button" href="#lab">開始動手試試看 <span>↓</span></a><div className="formula"><b>後驗機率</b><span>∝</span><b>似然</b><span>×</span><b>先驗機率</b></div></section>
    <section className="lab" id="lab"><Title n="01" title="先驗不是猜測，是起跑點" text="假設我們想判斷一枚硬幣正面朝上的機率。"/><div className="lab-grid"><div className="controls"><label>你原本相信正面機率是多少？ <strong>{prior}%</strong></label><input aria-label="先驗正面機率" type="range" min="10" max="90" value={prior} onChange={e=>setPrior(+e.target.value)}/><div className="range-labels"><span>偏向反面</span><span>公平硬幣</span><span>偏向正面</span></div><hr/><label>接著丟 10 次，觀察到幾次正面？ <strong>{heads} 次</strong></label><input aria-label="觀察到的正面次數" type="range" min="0" max="10" value={heads} onChange={e=>setHeads(+e.target.value)}/><div className="coins">{Array.from({length:10},(_,i)=><span className={i<heads?'head':''} key={i}>{i<heads?'正':'反'}</span>)}</div></div><div className="chart-card"><div className="legend"><span className="prior-dot">先驗</span><span className="post-dot">後驗</span></div><svg viewBox="0 0 100 52" role="img" aria-label="先驗與後驗分布曲線"><line x1="0" y1="46" x2="100" y2="46" stroke="#d7dde8"/><Curve a={a} b={b} color="#68758a"/><Curve a={pa} b={pb} color="#d6a531"/></svg><div className="axis"><span>0%</span><span>正面機率</span><span>100%</span></div><div className="result"><small>更新後最合理的估計</small><b>{posterior}%</b><p>資料把你的信念從 <strong>{prior}%</strong> 拉向觀察結果 <strong>{heads*10}%</strong>。</p></div></div></div></section>
    <section className="training" id="training"><Title n="02" title="持續觀測：訓練真的帶來進步嗎？" text="不限次數輸入每一批資料，持續觀察四種機率如何變化與收斂。"/><DemoButtons generate={generateDemo}/><div className="round-progress unlimited"><strong>{rounds.length}</strong><span>次觀測已確認</span><small>下一筆將是第 {rounds.length+1} 次</small></div><div className="training-grid"><div className="training-inputs"><NumberField label="本次訓練總人數" value={learners} set={setLearners}/><NumberField label="完課人數" value={completed} set={setCompleted}/><NumberField label="完課且主管認為有進步人數" value={completedImproved} set={setCompletedImproved}/><NumberField label="未完課但主管認為有進步人數" value={notCompletedImproved} set={setNotCompletedImproved}/><p className="input-note">未進步人數會自動由各組總數扣除有進步人數。超過合理範圍的輸入會以可成立的最大值計算。</p><button className="confirm-round" onClick={confirmRound}>{`確認第 ${rounds.length+1} 次輸入`}</button>{rounds.length>0&&<button className="reset-rounds" onClick={()=>setRounds([])}>清除全部觀測並重新開始</button>}</div><div className="matrix-wrap"><div className="matrix" role="table" aria-label="本次訓練完成與進步交叉表"><div/><b>有進步</b><b>未進步</b><strong>已完課</strong><Cell count={doneBetter} rate={pct(doneBetter,done)} tone="good"/><Cell count={doneSame} rate={pct(doneSame,done)} tone="warm"/><strong>未完課</strong><Cell count={notDoneBetter} rate={pct(notDoneBetter,notDone)} tone="cool"/><Cell count={notDoneSame} rate={pct(notDoneSame,notDone)} tone="plain"/></div><div className="effect-summary"><span>完課後進步率 <b>{pct(doneBetter,done)}</b></span><span>未完課進步率 <b>{pct(notDoneBetter,notDone)}</b></span><p>目前兩組進步率相差 <strong>{done&&notDone?`${((doneBetter/done-notDoneBetter/notDone)*100).toFixed(1)} 個百分點`:'—'}</strong>。</p></div></div></div>{rounds.length>0&&<div className="trend-section"><h3>歷次機率變化</h3><p>圖表會隨觀測次數向右延伸，可水平捲動查看全部資料。</p><TrendChart rounds={rounds}/><div className="final-probabilities">{series.map(s=><div key={s.key}><span>最新：{s.label}</span><b>{rounds[rounds.length-1][s.key].toFixed(1)}%</b></div>)}</div></div>}
    <div className="decision-lab"><div className="decision-head"><span>BAYESIAN DECISION LAB</span><h3>把比例變成可以決策的證據</h3><p>目前使用 {rounds.length||1} 次觀測、完課組 {dN} 人與未完課組 {nN} 人進行更新。</p></div><div className="prior-controls"><label>過去平均進步率 <b>{priorMean}%</b><input type="range" min="10" max="90" value={priorMean} onChange={e=>setPriorMean(+e.target.value)}/></label><label>先驗證據強度 <b>相當於 {priorStrength} 人</b><input type="range" min="2" max="30" value={priorStrength} onChange={e=>setPriorStrength(+e.target.value)}/></label><label>最低有意義效果 <b>{threshold} 個百分點</b><input type="range" min="0" max="30" value={threshold} onChange={e=>setThreshold(+e.target.value)}/></label></div><div className="decision-kpis"><article><small>完課組較有效的機率</small><b>{(probBetter*100).toFixed(1)}%</b><div className="prob-bar"><i style={{width:`${probBetter*100}%`}}/></div><p>{probBetter>.9?'證據方向明確':'目前仍有較多不確定性'}</p></article><article><small>效益超過門檻的機率</small><b>{(probThreshold*100).toFixed(1)}%</b><div className="prob-bar orange"><i style={{width:`${probThreshold*100}%`}}/></div><p>門檻：至少提升 {threshold} 個百分點</p></article><article><small>後驗平均效果差</small><b>{(diff*100).toFixed(1)}<em> 點</em></b><p>完課組減去未完課組</p></article></div><div className="credible"><h4>95% 可信區間</h4><div><span>完課組 <b>{(dMean*100).toFixed(1)}%</b></span><i><u style={{left:`${interval(dMean,dVar)[0]}%`,width:`${interval(dMean,dVar)[1]-interval(dMean,dVar)[0]}%`}}/><em style={{left:`${dMean*100}%`}}/></i><small>{interval(dMean,dVar)[0].toFixed(1)}–{interval(dMean,dVar)[1].toFixed(1)}%</small></div><div><span>未完課組 <b>{(nMean*100).toFixed(1)}%</b></span><i><u className="blue" style={{left:`${interval(nMean,nVar)[0]}%`,width:`${interval(nMean,nVar)[1]-interval(nMean,nVar)[0]}%`}}/><em style={{left:`${nMean*100}%`}}/></i><small>{interval(nMean,nVar)[0].toFixed(1)}–{interval(nMean,nVar)[1].toFixed(1)}%</small></div></div><div className="research-roadmap"><h4>下一步：從關聯走向因果</h4><div><span><b>1</b><strong>描述</strong><small>誰完課、誰進步？</small></span><i>→</i><span><b>2</b><strong>控制差異</strong><small>部門、年資、前測能力</small></span><i>→</i><span><b>3</b><strong>追蹤</strong><small>1、3、6 個月後還有效嗎？</small></span><i>→</i><span><b>4</b><strong>決策</strong><small>效果大到值得投資嗎？</small></span></div></div></div></section>
    <section className="compare" id="compare"><Title n="03" title="同一份資料，兩種提問方式" text="兩個學派不是誰對誰錯，而是回答不同的問題。"/><div className="compare-grid"><article><div className="tag">頻率學派</div><h3>如果假設不變，資料有多罕見？</h3><p>參數被視為固定但未知。重複抽樣很多次，以資料的長期頻率判斷結果。</p><blockquote>「若硬幣公平，像這樣的結果有多常發生？」</blockquote></article><div className="versus">VS</div><article className="bayes"><div className="tag">貝氏學派</div><h3>看到資料後，假設有多可信？</h3><p>未知參數可用機率分布描述。把先驗和新資料結合，直接更新我們的信念。</p><blockquote>「看到 7 次正面後，硬幣偏向正面的機率是多少？」</blockquote></article></div></section>
    <section className="case" id="case"><div className="case-copy"><span>04 · 生活案例</span><h2>醫療檢測陽性，<br/>不代表 99% 患病</h2><p>假設每 100 人有 1 人患病，檢測會驗出患者，但也會把 5 位健康者驗成陽性。疾病盛行率就是不可忽略的「先驗」。</p></div><div className="people"><div className="people-row">{Array.from({length:100},(_,i)=><i key={i} className={i===0?'sick':i<=5?'false':''}/>)}</div><div className="case-legend"><span><i className="sick"/>真正陽性 1 人</span><span><i className="false"/>偽陽性 5 人</span></div><div className="case-answer">檢測陽性者中，真正患病約為 <strong>1 / 6 ≈ 17%</strong></div></div></section>
    <footer><b>β 貝氏直覺室</b><p>帶著好奇心，讓證據更新你的看法。</p><a href="#top">回到頂端 ↑</a></footer>
    <BaselineInputs completedBefore={completedBefore} setCompletedBefore={setCompletedBefore} notCompletedBefore={notCompletedBefore} setNotCompletedBefore={setNotCompletedBefore}/>
    {rounds.length>0&&<GapChart rounds={rounds}/>} 
  </main>
}
